fix notg syntax error in javascript-jasmine
removed extra '.' in the javascript-jasmine.snippets
'notg' snippet which leads to a

SyntaxError: Unexpected token .

        expect(6)..not.toBeGreaterThan(7);
                  ^

if not removed